// ─── Features ────────────────────────────────────────────────────────────────
export const features = [
  {
    id: "crop-recommendation",
    title: "AI Crop Recommendation",
    shortDesc: "Personalised crop suggestions based on soil, season and market demand.",
    description: "Our AI analyses your soil type, location, water availability, historical weather and current market conditions to recommend the highest-yield, most profitable crops for your land — updated every season.",
    iconName: "Sprout",
    color: "text-emerald-600",
    bg: "bg-emerald-50",
    border: "border-emerald-100",
    howItWorks: [
      "Enter your location, soil type and available water sources",
      "AI cross-references 10 years of regional crop performance data",
      "Market demand analysis forecasts profitability per crop",
      "Receive a ranked crop list with expected yield and net income",
    ],
    benefits: ["35% average yield increase", "60% lower crop failure risk", "Season-specific advice", "Market-aligned selection"],
    stats: [{ label: "Avg. Yield Increase", value: "35%" }, { label: "Farmers Using", value: "8,500+" }, { label: "Accuracy", value: "94%" }, { label: "Crops Covered", value: "80+" }],
  },
  {
    id: "disease-detection",
    title: "Crop Disease Detection",
    shortDesc: "Upload a photo for instant AI disease diagnosis across 200+ conditions.",
    description: "Our deep-learning model trained on 500,000+ crop disease images identifies diseases in seconds. Take a photo of any affected plant and get a diagnosis with localised treatment recommendations and cost estimates.",
    iconName: "Microscope",
    color: "text-rose-600",
    bg: "bg-rose-50",
    border: "border-rose-100",
    howItWorks: [
      "Photograph your plant leaves or affected stem/root",
      "AI image recognition checks 200+ disease patterns instantly",
      "Cross-references active regional disease outbreak data",
      "Returns diagnosis with treatment plan and product suggestions",
    ],
    benefits: ["80% crop loss prevented", "Diagnosis in <3 seconds", "200+ diseases covered", "Localised treatments"],
    stats: [{ label: "Detection Accuracy", value: "96%" }, { label: "Diseases in DB", value: "200+" }, { label: "Crop Loss Saved", value: "80%" }, { label: "Daily Scans", value: "12K+" }],
  },
  {
    id: "smart-irrigation",
    title: "Smart Irrigation",
    shortDesc: "AI-optimised irrigation schedules saving 40% water on average.",
    description: "Save water and improve yield with irrigation schedules that combine real-time soil moisture readings, crop water requirements at each growth stage, and 7-day hyperlocal weather forecasts into one actionable daily plan.",
    iconName: "Droplets",
    color: "text-sky-600",
    bg: "bg-sky-50",
    border: "border-sky-100",
    howItWorks: [
      "Soil moisture sensors provide continuous field readings",
      "7-day hyperlocal weather forecast incorporated daily",
      "AI calculates precise water needs at each growth stage",
      "Daily irrigation schedule pushed to your mobile phone",
    ],
    benefits: ["40% water savings", "Prevents waterlogging", "Works with existing pumps", "Auto drought mode"],
    stats: [{ label: "Water Savings", value: "40%" }, { label: "Yield Improvement", value: "28%" }, { label: "Farms Optimised", value: "5,200+" }, { label: "Cost Reduction", value: "35%" }],
  },
  {
    id: "weather-prediction",
    title: "Weather Intelligence",
    shortDesc: "Hyperlocal 7-day forecasts with farming-specific alerts and advisories.",
    description: "Farm-level weather forecasts with harvest windows, frost warnings, rain alerts, spray timing advisories and humidity reports — all tailored specifically to your crop type, growth stage and geographic microzone.",
    iconName: "CloudRain",
    color: "text-blue-600",
    bg: "bg-blue-50",
    border: "border-blue-100",
    howItWorks: [
      "Hyperlocal weather stations provide field-level data",
      "AI combines satellite imagery with ground sensor readings",
      "Crop-specific impact analysis generates farming advisories",
      "Push notifications warn you 48 hours before adverse events",
    ],
    benefits: ["7-day planning confidence", "Avoid crop damage", "Optimal harvest windows", "Spray timing optimised"],
    stats: [{ label: "Forecast Accuracy", value: "92%" }, { label: "Alert Lead Time", value: "48 hrs" }, { label: "Districts Covered", value: "14" }, { label: "Alert Categories", value: "12" }],
  },
  {
    id: "market-price",
    title: "Market Price Prediction",
    shortDesc: "Real-time prices and 30-day AI forecasts from 200+ markets.",
    description: "Know exactly when and where to sell. Our AI price prediction engine analyses 200+ mandis, 10-year seasonal price cycles, supply chain dynamics, and demand patterns to tell you the right time and place to sell for maximum income.",
    iconName: "TrendingUp",
    color: "text-violet-600",
    bg: "bg-violet-50",
    border: "border-violet-100",
    howItWorks: [
      "Real-time price feeds from 200+ mandis across India",
      "AI analyses 10-year seasonal price cycles per crop",
      "Supply chain and logistics factors incorporated",
      "30-day price forecast with confidence intervals",
    ],
    benefits: ["22% income increase", "Best mandi comparison", "Plan harvest timing", "Cold storage ROI data"],
    stats: [{ label: "Price Accuracy", value: "89%" }, { label: "Income Increase", value: "22%" }, { label: "Markets Tracked", value: "200+" }, { label: "Crops Covered", value: "80+" }],
  },
  {
    id: "ai-assistant",
    title: "AI Farming Assistant",
    shortDesc: "Your personal farming expert — 24/7, in Malayalam and English.",
    description: "Chat with our AI assistant trained on Kerala and pan-India agricultural data. Get instant expert answers about crops, diseases, weather, market prices and government schemes — by text or voice, in your preferred language.",
    iconName: "Bot",
    color: "text-teal-600",
    bg: "bg-teal-50",
    border: "border-teal-100",
    howItWorks: [
      "Ask questions by text or voice in your language",
      "NLP model trained on 500K+ farming Q&As",
      "Connects to live weather, market and crop databases",
      "Personalises answers using your saved farm profile",
    ],
    benefits: ["Available 24/7", "Malayalam & English", "Voice support", "Connects all features"],
    stats: [{ label: "Daily Queries", value: "25K+" }, { label: "Satisfaction Rate", value: "97%" }, { label: "Response Time", value: "<2 sec" }, { label: "Languages", value: "3" }],
  },
  {
    id: "soil-health",
    title: "Soil Health Card",
    shortDesc: "Digital soil testing with NPK, pH and micronutrient breakdowns.",
    description: "Get a complete digital soil health report — nitrogen, phosphorus, potassium, pH, organic carbon and micronutrients — with AI-generated fertilizer and amendment plans tailored to your next crop cycle.",
    iconName: "Layers",
    color: "text-amber-700",
    bg: "bg-amber-50",
    border: "border-amber-100",
    howItWorks: [
      "Book a soil sample collection or submit lab results",
      "AI digitises and analyses NPK, pH and micronutrient levels",
      "Compares results against optimal ranges for your target crop",
      "Generates a fertilizer and soil-amendment plan automatically",
    ],
    benefits: ["Precise fertilizer dosing", "Reduces input cost 18%", "Tracks soil trends yearly", "Crop-specific plans"],
    stats: [{ label: "Soil Tests Digitised", value: "40K+" }, { label: "Input Cost Saved", value: "18%" }, { label: "Nutrients Tracked", value: "12" }, { label: "Report Time", value: "24 hrs" }],
  },
  {
    id: "iot-drone",
    title: "IoT & Drone Monitoring",
    shortDesc: "Connect field sensors and drones for real-time farm surveillance.",
    description: "Integrate soil-moisture sensors, weather stations and drone imagery into a single live dashboard. AI flags stressed zones, pest hotspots and irrigation issues before they're visible to the naked eye.",
    iconName: "Satellite",
    color: "text-indigo-600",
    bg: "bg-indigo-50",
    border: "border-indigo-100",
    howItWorks: [
      "Connect IoT sensors or upload drone/satellite imagery",
      "AI builds an NDVI crop-health map of your entire field",
      "Stress, pest and irrigation-issue zones flagged automatically",
      "Live dashboard updates with every new scan or sensor reading",
    ],
    benefits: ["Whole-field visibility", "Early stress detection", "Works with any sensor brand", "NDVI health mapping"],
    stats: [{ label: "Fields Mapped", value: "3,100+" }, { label: "Sensors Connected", value: "9,800+" }, { label: "Early Alerts/mo", value: "1,400+" }, { label: "Coverage Accuracy", value: "95%" }],
  },
  {
    id: "govt-schemes",
    title: "Government Scheme Advisor",
    shortDesc: "Matches you to subsidies, loans and schemes you're eligible for.",
    description: "Never miss a subsidy again. Our AI matches your farm profile — crop, land size, location and income — against central and state government schemes, and walks you through eligibility and application steps.",
    iconName: "Landmark",
    color: "text-emerald-700",
    bg: "bg-emerald-50",
    border: "border-emerald-100",
    howItWorks: [
      "AI reads your saved farm profile (crop, land, location, income)",
      "Matches against 150+ active central and state schemes",
      "Ranks schemes by eligibility likelihood and benefit value",
      "Step-by-step application guidance with document checklist",
    ],
    benefits: ["150+ schemes tracked", "Personalised matches", "Application checklists", "Deadline reminders"],
    stats: [{ label: "Schemes Tracked", value: "150+" }, { label: "Farmers Matched", value: "6,700+" }, { label: "Avg. Subsidy Found", value: "₹18K" }, { label: "Approval Rate", value: "78%" }],
  },
  {
    id: "crop-insurance",
    title: "Crop Insurance Assistant",
    shortDesc: "AI-simplified insurance comparison, claims and payout tracking.",
    description: "Compare crop insurance policies in plain language, get AI help filing claims after weather damage or pest loss, and track your payout status — all without wading through complex policy documents.",
    iconName: "ShieldCheck",
    color: "text-cyan-700",
    bg: "bg-cyan-50",
    border: "border-cyan-100",
    howItWorks: [
      "Compare available crop insurance policies for your region",
      "AI explains coverage, premium and exclusions in plain language",
      "Guides you through evidence collection after crop damage",
      "Tracks claim status until payout is received",
    ],
    benefits: ["Plain-language policy comparison", "Guided claims filing", "Payout status tracking", "Damage evidence checklist"],
    stats: [{ label: "Claims Assisted", value: "2,300+" }, { label: "Avg. Claim Time Saved", value: "9 days" }, { label: "Policies Compared", value: "35+" }, { label: "Payout Success Rate", value: "91%" }],
  },
  {
    id: "community",
    title: "Farmer Community Forum",
    shortDesc: "Ask, share and learn from verified farmers in your district.",
    description: "Join district-level farmer groups to share what's working, ask questions, post crop photos and get answers from experienced local farmers and agronomists — moderated and translated automatically.",
    iconName: "Users",
    color: "text-fuchsia-700",
    bg: "bg-fuchsia-50",
    border: "border-fuchsia-100",
    howItWorks: [
      "Join your district's verified farmer community group",
      "Post questions, crop photos or market tips",
      "AI auto-translates posts across Malayalam, English & Tamil",
      "Get answers from local farmers and agronomists, ranked by trust score",
    ],
    benefits: ["District-level groups", "Auto-translation", "Verified expert answers", "Photo-based Q&A"],
    stats: [{ label: "Active Members", value: "14,200+" }, { label: "Daily Posts", value: "600+" }, { label: "Districts Active", value: "14" }, { label: "Avg. Response Time", value: "22 min" }],
  },
];

// ─── Market Crops ─────────────────────────────────────────────────────────────
export const marketCrops = [
  {
    id: "rice",
    name: "Rice",
    fullName: "Rice (Paddy)",
    emoji: "🌾",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹2,180",
    prevPrice: "₹2,110",
    change: "+3.3%",
    up: true,
    demand: "High",
    supply: "Medium",
    category: "Cereals",
    prediction: "₹2,280 (30d)",
    bestLocations: ["Palakkad", "Alappuzha", "Kuttanad"],
    aiRec: "sell-now",
    aiRecText: "Strong procurement demand. Prices rising 3–5% over next 30 days. Sell now at Palakkad mandi for best returns.",
    priceHistory: [
      { month: "Jan", price: 2050 }, { month: "Feb", price: 2080 }, { month: "Mar", price: 2010 },
      { month: "Apr", price: 2090 }, { month: "May", price: 2150 }, { month: "Jun", price: 2110 }, { month: "Jul", price: 2180 },
    ],
  },
  {
    id: "wheat",
    name: "Wheat",
    fullName: "Wheat",
    emoji: "🌿",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹1,950",
    prevPrice: "₹2,020",
    change: "-3.5%",
    up: false,
    demand: "Medium",
    supply: "High",
    category: "Cereals",
    prediction: "₹1,880 (30d)",
    bestLocations: ["Thrissur", "Ernakulam", "Kozhikode"],
    aiRec: "sell-now",
    aiRecText: "Prices declining due to high national stock. Sell within 2 weeks before further drop. Thrissur mandi offers best current rates.",
    priceHistory: [
      { month: "Jan", price: 2100 }, { month: "Feb", price: 2080 }, { month: "Mar", price: 2050 },
      { month: "Apr", price: 2020 }, { month: "May", price: 2010 }, { month: "Jun", price: 2020 }, { month: "Jul", price: 1950 },
    ],
  },
  {
    id: "corn",
    name: "Corn",
    fullName: "Corn (Maize)",
    emoji: "🌽",
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹1,680",
    prevPrice: "₹1,620",
    change: "+3.7%",
    up: true,
    demand: "High",
    supply: "Low",
    category: "Cereals",
    prediction: "₹1,820 (30d)",
    bestLocations: ["Wayanad", "Malappuram", "Palakkad"],
    aiRec: "wait",
    aiRecText: "Poultry feed demand driving prices up steadily. Wait 2–3 weeks for peak. Expected to reach ₹1,820 by end of August.",
    priceHistory: [
      { month: "Jan", price: 1500 }, { month: "Feb", price: 1540 }, { month: "Mar", price: 1580 },
      { month: "Apr", price: 1600 }, { month: "May", price: 1620 }, { month: "Jun", price: 1620 }, { month: "Jul", price: 1680 },
    ],
  },
  {
    id: "tapioca",
    name: "Tapioca",
    fullName: "Tapioca (Cassava)",
    emoji: "🍠",
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹18/kg",
    prevPrice: "₹16/kg",
    change: "+12.5%",
    up: true,
    demand: "Medium",
    supply: "Medium",
    category: "Tubers",
    prediction: "₹19/kg (30d)",
    bestLocations: ["Kottayam", "Thiruvananthapuram"],
    aiRec: "hold",
    aiRecText: "Steady local demand for starch and food use. Prices trending mildly upward — hold if storage allows.",
    priceHistory: [{ month: "Jan", price: 14 }, { month: "Feb", price: 14 }, { month: "Mar", price: 15 }, { month: "Apr", price: 15 }, { month: "May", price: 15 }, { month: "Jun", price: 16 }, { month: "Jul", price: 18 }],
  },
  {
    id: "ragi",
    name: "Ragi",
    fullName: "Ragi (Finger Millet)",
    emoji: "🌾",
    image: "https://images.unsplash.com/photo-1627843563095-f6e94676cfe0?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹3,850",
    prevPrice: "₹3,600",
    change: "+6.9%",
    up: true,
    demand: "High",
    supply: "Low",
    category: "Millets",
    prediction: "₹4,050 (30d)",
    bestLocations: ["Palakkad", "Wayanad"],
    aiRec: "increase-production",
    aiRecText: "Health-food demand for millets rising fast, MSP support strong. Good crop to expand into this season.",
    priceHistory: [{ month: "Jan", price: 3300 }, { month: "Feb", price: 3350 }, { month: "Mar", price: 3400 }, { month: "Apr", price: 3450 }, { month: "May", price: 3500 }, { month: "Jun", price: 3600 }, { month: "Jul", price: 3850 }],
  },
  {
    id: "cotton",
    name: "Cotton",
    fullName: "Cotton",
    emoji: "☁️",
    image: "https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹6,400",
    prevPrice: "₹6,100",
    change: "+4.9%",
    up: true,
    demand: "High",
    supply: "Low",
    category: "Fiber Crops",
    prediction: "₹6,900 (30d)",
    bestLocations: ["Palakkad", "Thrissur", "Malappuram"],
    aiRec: "increase-production",
    aiRecText: "Textile industry demand surge. Prices predicted to rise another 8% in 30 days. Increase production area if possible for next season.",
    priceHistory: [
      { month: "Jan", price: 5800 }, { month: "Feb", price: 5900 }, { month: "Mar", price: 6000 },
      { month: "Apr", price: 6100 }, { month: "May", price: 6150 }, { month: "Jun", price: 6100 }, { month: "Jul", price: 6400 },
    ],
  },
  {
    id: "vegetables",
    name: "Vegetables",
    fullName: "Vegetables (Mixed)",
    emoji: "🥬",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹48/kg",
    prevPrice: "₹42/kg",
    change: "+14.3%",
    up: true,
    demand: "High",
    supply: "Low",
    category: "Horticulture",
    prediction: "₹38/kg (30d)",
    bestLocations: ["Thrissur", "Kozhikode", "Ernakulam"],
    aiRec: "sell-now",
    aiRecText: "Monsoon disrupted Tamil Nadu supply causing spike. Prices will fall 20% in 3–4 weeks as local harvest arrives. Sell immediately.",
    priceHistory: [
      { month: "Jan", price: 35 }, { month: "Feb", price: 38 }, { month: "Mar", price: 42 },
      { month: "Apr", price: 40 }, { month: "May", price: 38 }, { month: "Jun", price: 42 }, { month: "Jul", price: 48 },
    ],
  },
  {
    id: "sugarcane", name: "Sugarcane", fullName: "Sugarcane", emoji: "🎋",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹340/qt", prevPrice: "₹325/qt", change: "+4.6%", up: true, demand: "High", supply: "Medium",
    category: "Cash Crops", prediction: "₹360/qt (30d)", bestLocations: ["Palakkad", "Malappuram", "Kozhikode"],
    aiRec: "hold", aiRecText: "Mill procurement price notified higher this season. Stable demand — hold for contracted mill delivery for best returns.",
    priceHistory: [{ month: "Jan", price: 300 }, { month: "Feb", price: 305 }, { month: "Mar", price: 310 }, { month: "Apr", price: 315 }, { month: "May", price: 320 }, { month: "Jun", price: 325 }, { month: "Jul", price: 340 }],
  },
  {
    id: "groundnut", name: "Groundnut", fullName: "Groundnut (Peanut)", emoji: "🥜",
    image: "https://images.unsplash.com/photo-1567892737950-30c4db37cd89?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹5,850", prevPrice: "₹5,600", change: "+4.5%", up: true, demand: "High", supply: "Low",
    category: "Oilseeds", prediction: "₹6,150 (30d)", bestLocations: ["Palakkad", "Thrissur"],
    aiRec: "increase-production", aiRecText: "Edible oil demand pushing groundnut prices up steadily. Good season to expand acreage if rotation allows.",
    priceHistory: [{ month: "Jan", price: 5200 }, { month: "Feb", price: 5300 }, { month: "Mar", price: 5400 }, { month: "Apr", price: 5450 }, { month: "May", price: 5500 }, { month: "Jun", price: 5600 }, { month: "Jul", price: 5850 }],
  },
  {
    id: "soybean", name: "Soybean", fullName: "Soybean", emoji: "🫘",
    image: "https://images.unsplash.com/photo-1620200423727-8127f75d7f53?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹4,320", prevPrice: "₹4,480", change: "-3.6%", up: false, demand: "Medium", supply: "High",
    category: "Oilseeds", prediction: "₹4,150 (30d)", bestLocations: ["Wayanad", "Idukki"],
    aiRec: "sell-now", aiRecText: "Bumper national harvest pushing prices down. Sell within 2 weeks before further softening.",
    priceHistory: [{ month: "Jan", price: 4600 }, { month: "Feb", price: 4550 }, { month: "Mar", price: 4500 }, { month: "Apr", price: 4480 }, { month: "May", price: 4460 }, { month: "Jun", price: 4480 }, { month: "Jul", price: 4320 }],
  },
  {
    id: "mustard", name: "Mustard", fullName: "Mustard (Sarson)", emoji: "🌼",
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹5,480", prevPrice: "₹5,320", change: "+3.0%", up: true, demand: "High", supply: "Medium",
    category: "Oilseeds", prediction: "₹5,700 (30d)", bestLocations: ["Palakkad", "Kannur"],
    aiRec: "wait", aiRecText: "Mustard oil demand rising ahead of festival season. Prices expected to firm up further — wait 2 weeks.",
    priceHistory: [{ month: "Jan", price: 5100 }, { month: "Feb", price: 5150 }, { month: "Mar", price: 5200 }, { month: "Apr", price: 5250 }, { month: "May", price: 5280 }, { month: "Jun", price: 5320 }, { month: "Jul", price: 5480 }],
  },
  {
    id: "chickpea", name: "Chickpea", fullName: "Chickpea (Chana)", emoji: "🫛",
    image: "https://images.unsplash.com/photo-1610725664285-7c57e6eeac3f?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹6,150", prevPrice: "₹5,900", change: "+4.2%", up: true, demand: "High", supply: "Low",
    category: "Pulses", prediction: "₹6,450 (30d)", bestLocations: ["Palakkad", "Thrissur"],
    aiRec: "sell-now", aiRecText: "Strong dal-mill demand and tight supply. Prices at multi-month high — good time to sell.",
    priceHistory: [{ month: "Jan", price: 5600 }, { month: "Feb", price: 5700 }, { month: "Mar", price: 5750 }, { month: "Apr", price: 5800 }, { month: "May", price: 5850 }, { month: "Jun", price: 5900 }, { month: "Jul", price: 6150 }],
  },
  {
    id: "green-gram", name: "Green Gram", fullName: "Green Gram (Moong)", emoji: "🟢",
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹7,800", prevPrice: "₹7,600", change: "+2.6%", up: true, demand: "Medium", supply: "Medium",
    category: "Pulses", prediction: "₹8,000 (30d)", bestLocations: ["Palakkad", "Malappuram"],
    aiRec: "hold", aiRecText: "Steady demand, mild upward trend. Hold for a few more weeks for a slightly better price.",
    priceHistory: [{ month: "Jan", price: 7400 }, { month: "Feb", price: 7450 }, { month: "Mar", price: 7500 }, { month: "Apr", price: 7500 }, { month: "May", price: 7550 }, { month: "Jun", price: 7600 }, { month: "Jul", price: 7800 }],
  },
  {
    id: "tomato", name: "Tomato", fullName: "Tomato", emoji: "🍅",
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹32/kg", prevPrice: "₹22/kg", change: "+45.5%", up: true, demand: "High", supply: "Low",
    category: "Vegetables", prediction: "₹24/kg (30d)", bestLocations: ["Kozhikode", "Thrissur"],
    aiRec: "sell-now", aiRecText: "Supply disruption from neighbouring states spiked prices sharply. Expect correction in 3 weeks — sell now.",
    priceHistory: [{ month: "Jan", price: 18 }, { month: "Feb", price: 20 }, { month: "Mar", price: 22 }, { month: "Apr", price: 20 }, { month: "May", price: 22 }, { month: "Jun", price: 22 }, { month: "Jul", price: 32 }],
  },
  {
    id: "onion", name: "Onion", fullName: "Onion", emoji: "🧅",
    image: "https://images.unsplash.com/photo-1508747703725-719777637510?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹28/kg", prevPrice: "₹31/kg", change: "-9.7%", up: false, demand: "Medium", supply: "High",
    category: "Vegetables", prediction: "₹25/kg (30d)", bestLocations: ["Palakkad", "Ernakulam"],
    aiRec: "sell-now", aiRecText: "New harvest arrivals increasing supply. Prices set to soften further — sell current stock now.",
    priceHistory: [{ month: "Jan", price: 34 }, { month: "Feb", price: 33 }, { month: "Mar", price: 32 }, { month: "Apr", price: 31 }, { month: "May", price: 30 }, { month: "Jun", price: 31 }, { month: "Jul", price: 28 }],
  },
  {
    id: "potato", name: "Potato", fullName: "Potato", emoji: "🥔",
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹22/kg", prevPrice: "₹20/kg", change: "+10.0%", up: true, demand: "Medium", supply: "Medium",
    category: "Vegetables", prediction: "₹24/kg (30d)", bestLocations: ["Idukki", "Wayanad"],
    aiRec: "hold", aiRecText: "Cold-storage stocks depleting, demand steady. Modest upward trend expected — hold a few weeks.",
    priceHistory: [{ month: "Jan", price: 18 }, { month: "Feb", price: 18 }, { month: "Mar", price: 19 }, { month: "Apr", price: 19 }, { month: "May", price: 20 }, { month: "Jun", price: 20 }, { month: "Jul", price: 22 }],
  },
  {
    id: "banana", name: "Banana", fullName: "Banana", emoji: "🍌",
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹34/kg", prevPrice: "₹31/kg", change: "+9.7%", up: true, demand: "High", supply: "Medium",
    category: "Fruits", prediction: "₹37/kg (30d)", bestLocations: ["Thrissur", "Palakkad", "Kozhikode"],
    aiRec: "sell-now", aiRecText: "Festival season demand rising sharply. Prices trending up — good window to sell ripe bunches now.",
    priceHistory: [{ month: "Jan", price: 26 }, { month: "Feb", price: 27 }, { month: "Mar", price: 28 }, { month: "Apr", price: 29 }, { month: "May", price: 30 }, { month: "Jun", price: 31 }, { month: "Jul", price: 34 }],
  },
  {
    id: "mango", name: "Mango", fullName: "Mango", emoji: "🥭",
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹65/kg", prevPrice: "₹58/kg", change: "+12.1%", up: true, demand: "High", supply: "Low",
    category: "Fruits", prediction: "₹72/kg (30d)", bestLocations: ["Malappuram", "Palakkad"],
    aiRec: "sell-now", aiRecText: "Peak season demand with export orders rising. Best prices of the year right now — sell without delay.",
    priceHistory: [{ month: "Jan", price: 40 }, { month: "Feb", price: 42 }, { month: "Mar", price: 46 }, { month: "Apr", price: 52 }, { month: "May", price: 58 }, { month: "Jun", price: 58 }, { month: "Jul", price: 65 }],
  },
  {
    id: "coconut", name: "Coconut", fullName: "Coconut", emoji: "🥥",
    image: "https://images.unsplash.com/photo-1580984969071-a8da5656c2fb?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹28/nut", prevPrice: "₹26/nut", change: "+7.7%", up: true, demand: "High", supply: "Medium",
    category: "Plantation Crops", prediction: "₹30/nut (30d)", bestLocations: ["Ernakulam", "Thrissur", "Kozhikode"],
    aiRec: "hold", aiRecText: "Copra and oil demand steady, prices firming gradually. Hold for another 2–3 weeks for a better rate.",
    priceHistory: [{ month: "Jan", price: 24 }, { month: "Feb", price: 24 }, { month: "Mar", price: 25 }, { month: "Apr", price: 25 }, { month: "May", price: 26 }, { month: "Jun", price: 26 }, { month: "Jul", price: 28 }],
  },
  {
    id: "pepper", name: "Black Pepper", fullName: "Black Pepper", emoji: "⚫",
    image: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹680/kg", prevPrice: "₹640/kg", change: "+6.3%", up: true, demand: "High", supply: "Low",
    category: "Spices", prediction: "₹720/kg (30d)", bestLocations: ["Wayanad", "Idukki", "Kannur"],
    aiRec: "sell-now", aiRecText: "Global supply tightness driving Kerala pepper prices up. Export enquiries strong — sell now for best returns.",
    priceHistory: [{ month: "Jan", price: 580 }, { month: "Feb", price: 590 }, { month: "Mar", price: 600 }, { month: "Apr", price: 610 }, { month: "May", price: 620 }, { month: "Jun", price: 640 }, { month: "Jul", price: 680 }],
  },
  {
    id: "cardamom", name: "Cardamom", fullName: "Cardamom (Elaichi)", emoji: "🟩",
    image: "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹1,850/kg", prevPrice: "₹1,720/kg", change: "+7.6%", up: true, demand: "High", supply: "Low",
    category: "Spices", prediction: "₹1,980/kg (30d)", bestLocations: ["Idukki"],
    aiRec: "sell-now", aiRecText: "Auction prices climbing on strong Gulf export demand. Idukki auctions currently offering the best rates.",
    priceHistory: [{ month: "Jan", price: 1500 }, { month: "Feb", price: 1550 }, { month: "Mar", price: 1600 }, { month: "Apr", price: 1650 }, { month: "May", price: 1680 }, { month: "Jun", price: 1720 }, { month: "Jul", price: 1850 }],
  },
  {
    id: "turmeric", name: "Turmeric", fullName: "Turmeric (Haldi)", emoji: "🟡",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹142/kg", prevPrice: "₹135/kg", change: "+5.2%", up: true, demand: "Medium", supply: "Medium",
    category: "Spices", prediction: "₹150/kg (30d)", bestLocations: ["Wayanad", "Kannur"],
    aiRec: "hold", aiRecText: "Domestic and export demand both stable. Slight upward trend — hold for a few more weeks.",
    priceHistory: [{ month: "Jan", price: 120 }, { month: "Feb", price: 122 }, { month: "Mar", price: 125 }, { month: "Apr", price: 128 }, { month: "May", price: 130 }, { month: "Jun", price: 135 }, { month: "Jul", price: 142 }],
  },
  {
    id: "ginger", name: "Ginger", fullName: "Ginger", emoji: "🫚",
    image: "https://images.unsplash.com/photo-1599909533144-08fd7c1c0f7a?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹98/kg", prevPrice: "₹110/kg", change: "-10.9%", up: false, demand: "Medium", supply: "High",
    category: "Spices", prediction: "₹88/kg (30d)", bestLocations: ["Wayanad", "Idukki"],
    aiRec: "sell-now", aiRecText: "Fresh harvest flooding the market, prices softening. Sell existing stock now before further decline.",
    priceHistory: [{ month: "Jan", price: 130 }, { month: "Feb", price: 125 }, { month: "Mar", price: 120 }, { month: "Apr", price: 115 }, { month: "May", price: 112 }, { month: "Jun", price: 110 }, { month: "Jul", price: 98 }],
  },
  {
    id: "tea", name: "Tea", fullName: "Tea (Green Leaf)", emoji: "🍃",
    image: "https://images.unsplash.com/photo-1546469599-64a8c1e13a30?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹22/kg", prevPrice: "₹20/kg", change: "+10.0%", up: true, demand: "Medium", supply: "Medium",
    category: "Plantation Crops", prediction: "₹23/kg (30d)", bestLocations: ["Idukki", "Wayanad"],
    aiRec: "hold", aiRecText: "Factory procurement prices firming with peak season quality leaf. Hold for consistent factory rates.",
    priceHistory: [{ month: "Jan", price: 17 }, { month: "Feb", price: 18 }, { month: "Mar", price: 18 }, { month: "Apr", price: 19 }, { month: "May", price: 19 }, { month: "Jun", price: 20 }, { month: "Jul", price: 22 }],
  },
  {
    id: "coffee", name: "Coffee", fullName: "Coffee (Robusta)", emoji: "☕",
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹8,200/qt", prevPrice: "₹7,600/qt", change: "+7.9%", up: true, demand: "High", supply: "Low",
    category: "Plantation Crops", prediction: "₹8,700/qt (30d)", bestLocations: ["Wayanad", "Idukki"],
    aiRec: "sell-now", aiRecText: "Global coffee prices at multi-year highs on tight supply. Excellent selling window right now.",
    priceHistory: [{ month: "Jan", price: 6600 }, { month: "Feb", price: 6800 }, { month: "Mar", price: 7000 }, { month: "Apr", price: 7200 }, { month: "May", price: 7400 }, { month: "Jun", price: 7600 }, { month: "Jul", price: 8200 }],
  },
  {
    id: "rubber", name: "Rubber", fullName: "Natural Rubber", emoji: "🌳",
    image: "https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=400&h=240&fit=crop&auto=format",
    currentPrice: "₹185/kg", prevPrice: "₹178/kg", change: "+3.9%", up: true, demand: "Medium", supply: "Medium",
    category: "Plantation Crops", prediction: "₹192/kg (30d)", bestLocations: ["Kottayam", "Ernakulam"],
    aiRec: "hold", aiRecText: "Tyre-industry demand steady, prices gradually improving. Hold sheet stock for slightly better rates.",
    priceHistory: [{ month: "Jan", price: 165 }, { month: "Feb", price: 168 }, { month: "Mar", price: 170 }, { month: "Apr", price: 172 }, { month: "May", price: 175 }, { month: "Jun", price: 178 }, { month: "Jul", price: 185 }],
  },
];

// ─── Farm Crops (My Farm) ─────────────────────────────────────────────────────
export const farmCrops = [
  {
    id: "rice",
    name: "Rice",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500&h=280&fit=crop&auto=format",
    area: "2.4 acres",
    stage: "Tillering",
    health: 94,
    daysLeft: 45,
    water: "8–10 cm standing water — maintain for 2 more weeks",
    fertilizer: "Urea 50 kg/ha + MOP 25 kg/ha — apply in 3 days",
    expectedYield: "28 quintals / acre",
    nextAction: "Apply nitrogen fertilizer before Thursday rain",
    stages: [{ s: "Germination", done: true }, { s: "Seedling", done: true }, { s: "Tillering", done: false }, { s: "Panicle Init.", done: false }, { s: "Heading", done: false }, { s: "Harvest", done: false }],
    aiNote: "Crop at 94% health. Urea application before Thursday's forecast rain will maximise nitrogen uptake. Monitor for Brown Plant Hopper — active in your district this week.",
  },
  {
    id: "wheat",
    name: "Wheat",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=500&h=280&fit=crop&auto=format",
    area: "1.6 acres",
    stage: "Grain Filling",
    health: 88,
    daysLeft: 18,
    water: "Last irrigation — reduce water for grain hardening",
    fertilizer: "No fertilizer needed — maturity stage",
    expectedYield: "22 quintals / acre",
    nextAction: "Prepare harvest equipment — 18 days to harvest",
    stages: [{ s: "Germination", done: true }, { s: "Tillering", done: true }, { s: "Jointing", done: true }, { s: "Grain Filling", done: false }, { s: "Maturity", done: false }, { s: "Harvest", done: false }],
    aiNote: "Grain filling stage progressing well. Current market price ₹1,950/qt with downward trend. Harvest on schedule — post-harvest sell within 2 weeks for best value.",
  },
  {
    id: "corn",
    name: "Corn",
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=500&h=280&fit=crop&auto=format",
    area: "0.8 acres",
    stage: "Tasseling",
    health: 91,
    daysLeft: 35,
    water: "Critical water period — irrigate every 5 days",
    fertilizer: "K₂O 60 kg/ha — apply immediately for cob development",
    expectedYield: "32 quintals / acre",
    nextAction: "Apply potassium fertilizer — cob development phase",
    stages: [{ s: "Germination", done: true }, { s: "Vegetative", done: true }, { s: "Tasseling", done: false }, { s: "Silking", done: false }, { s: "Grain Fill", done: false }, { s: "Harvest", done: false }],
    aiNote: "Tasseling stage requires maximum nutrition. Prices rising — consider waiting to sell until late August for ₹1,820 target. Stem borer alert in neighbouring farms — inspect weekly.",
  },
  {
    id: "cotton",
    name: "Cotton",
    image: "https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=500&h=280&fit=crop&auto=format",
    area: "1.2 acres",
    stage: "Boll Formation",
    health: 85,
    daysLeft: 60,
    water: "Moderate watering — 1 irrigation per week",
    fertilizer: "Boron spray 0.1% — improves boll retention",
    expectedYield: "12 quintals / acre",
    nextAction: "Boron foliar spray — prevents boll drop",
    stages: [{ s: "Germination", done: true }, { s: "Squaring", done: true }, { s: "Flowering", done: true }, { s: "Boll Form.", done: false }, { s: "Boll Open", done: false }, { s: "Harvest", done: false }],
    aiNote: "Boll formation at 85% — slightly below optimal. Boron spray will prevent boll drop and improve fibre quality. Cotton prices at 4-year high — excellent harvest outlook at current market.",
  },
];

// ─── Admin Users / Farmers ────────────────────────────────────────────────────
export const adminFarmers = [
  { id: "f1", name: "Rajan Nair", email: "rajan@example.com", phone: "+91 94470 12345", location: "Palakkad", crop: "Rice & Wheat", area: "4.0 ac", status: "Active", joined: "Mar 2023", lastActive: "2 hrs ago", yieldGain: "+38%" },
  { id: "f2", name: "Meera Krishnan", email: "meera@example.com", phone: "+91 98450 67890", location: "Thrissur", crop: "Vegetables", area: "1.8 ac", status: "Active", joined: "May 2023", lastActive: "1 day ago", yieldGain: "+24%" },
  { id: "f3", name: "Suresh Pillai", email: "suresh@example.com", phone: "+91 96330 11122", location: "Wayanad", crop: "Corn & Pepper", area: "5.6 ac", status: "Active", joined: "Jun 2023", lastActive: "3 hrs ago", yieldGain: "+29%" },
  { id: "f4", name: "Asha Thomas", email: "asha@example.com", phone: "+91 95120 44556", location: "Kottayam", crop: "Rubber", area: "8.2 ac", status: "Inactive", joined: "Jul 2023", lastActive: "2 weeks ago", yieldGain: "+12%" },
  { id: "f5", name: "Binu George", email: "binu@example.com", phone: "+91 99480 77889", location: "Ernakulam", crop: "Coconut", area: "2.4 ac", status: "Active", joined: "Aug 2023", lastActive: "5 hrs ago", yieldGain: "+21%" },
  { id: "f6", name: "Lekha Menon", email: "lekha@example.com", phone: "+91 97110 33445", location: "Alappuzha", crop: "Rice", area: "4.1 ac", status: "Active", joined: "Sep 2023", lastActive: "30 min ago", yieldGain: "+41%" },
  { id: "f7", name: "Vijayan Kumar", email: "vijayan@example.com", phone: "+91 94850 99001", location: "Malappuram", crop: "Banana & Cotton", area: "1.2 ac", status: "Active", joined: "Oct 2023", lastActive: "1 hr ago", yieldGain: "+18%" },
  { id: "f8", name: "Sindhu Raj", email: "sindhu@example.com", phone: "+91 98230 22334", location: "Kozhikode", crop: "Vegetables", area: "0.8 ac", status: "Inactive", joined: "Nov 2023", lastActive: "1 month ago", yieldGain: "+9%" },
];

// ─── Charts Data ──────────────────────────────────────────────────────────────
export const analyticsData = [
  { month: "Jan", farmers: 7800, sessions: 22000, revenue: 390000 },
  { month: "Feb", farmers: 8400, sessions: 26000, revenue: 440000 },
  { month: "Mar", farmers: 8900, sessions: 31000, revenue: 510000 },
  { month: "Apr", farmers: 9600, sessions: 39000, revenue: 600000 },
  { month: "May", farmers: 10200, sessions: 45000, revenue: 680000 },
  { month: "Jun", farmers: 10800, sessions: 51000, revenue: 770000 },
  { month: "Jul", farmers: 11500, sessions: 58000, revenue: 880000 },
];

export const cropStats = [
  { crop: "Rice", count: 4200 }, { crop: "Wheat", count: 2800 }, { crop: "Corn", count: 1900 },
  { crop: "Cotton", count: 1600 }, { crop: "Vegetables", count: 1000 },
];

export const demandPie = [
  { name: "Rice", value: 35, color: "#1B5E38" },
  { name: "Vegetables", value: 25, color: "#4ADE80" },
  { name: "Corn", value: 18, color: "#0EA5E9" },
  { name: "Cotton", value: 12, color: "#F59E0B" },
  { name: "Wheat", value: 10, color: "#8B5CF6" },
];

export const weatherForecast = [
  { day: "Today", high: 31, low: 24, rain: 20, icon: "☀️", desc: "Sunny" },
  { day: "Tue", high: 29, low: 23, rain: 65, icon: "🌧️", desc: "Rain" },
  { day: "Wed", high: 27, low: 22, rain: 82, icon: "⛈️", desc: "Storm" },
  { day: "Thu", high: 30, low: 24, rain: 40, icon: "⛅", desc: "Cloudy" },
  { day: "Fri", high: 32, low: 25, rain: 12, icon: "☀️", desc: "Sunny" },
  { day: "Sat", high: 33, low: 26, rain: 8, icon: "☀️", desc: "Clear" },
  { day: "Sun", high: 28, low: 23, rain: 50, icon: "🌦️", desc: "Light Rain" },
];

export const sampleChat = [
  { role: "ai", text: "Hello! I'm your FARMO AI assistant 🌱 I can help with crop recommendations, disease detection, weather, market prices and farming advice. What do you need help with today?" },
  { role: "user", text: "What fertilizer should I use for my rice crop at tillering stage?" },
  { role: "ai", text: "For rice at the tillering stage, apply Urea (46-0-0) at 50 kg/ha as top-dressing. For best results, apply it before the forecast rain on Thursday — the water will help the nitrogen absorb into the soil. Avoid applying after 6 PM to reduce volatilisation losses." },
  { role: "user", text: "When should I sell my corn harvest?" },
  { role: "ai", text: "Based on current market data, corn prices in your area are at ₹1,680/qt and are predicted to rise to ₹1,820 in 3 weeks due to growing poultry feed demand. I recommend waiting 2–3 weeks for the price peak, then selling at the Wayanad or Malappuram mandi for maximum returns." },
];

export const cropDatabase = [
  { name: "Paddy (Rice)", area: "38,400 ac", health: 91, farmers: 4200, season: "Kharif", status: "Growing" },
  { name: "Wheat", area: "22,800 ac", health: 87, farmers: 2800, season: "Rabi", status: "Harvesting" },
  { name: "Corn (Maize)", area: "12,600 ac", health: 88, farmers: 1900, season: "Kharif", status: "Growing" },
  { name: "Cotton", area: "8,600 ac", health: 84, farmers: 1600, season: "Kharif", status: "Boll Formation" },
  { name: "Vegetables", area: "5,200 ac", health: 93, farmers: 1000, season: "Year-round", status: "Ready" },
  { name: "Coconut", area: "18,200 ac", health: 89, farmers: 2200, season: "Perennial", status: "Harvesting" },
];

export const marketPriceTable = [
  { crop: "Rice", current: "₹2,180", prev: "₹2,110", trend: "+3.3%", up: true, prediction: "₹2,280" },
  { crop: "Wheat", current: "₹1,950", prev: "₹2,020", trend: "-3.5%", up: false, prediction: "₹1,880" },
  { crop: "Corn", current: "₹1,680", prev: "₹1,620", trend: "+3.7%", up: true, prediction: "₹1,820" },
  { crop: "Cotton", current: "₹6,400", prev: "₹6,100", trend: "+4.9%", up: true, prediction: "₹6,900" },
  { crop: "Coconut", current: "₹28/nut", prev: "₹26/nut", trend: "+7.7%", up: true, prediction: "₹30/nut" },
  { crop: "Banana", current: "₹34/kg", prev: "₹31/kg", trend: "+9.7%", up: true, prediction: "₹37/kg" },
  { crop: "Black Pepper", current: "₹680/kg", prev: "₹640/kg", trend: "+6.3%", up: true, prediction: "₹720/kg" },
  { crop: "Rubber", current: "₹185/kg", prev: "₹178/kg", trend: "+3.9%", up: true, prediction: "₹192/kg" },
];

export const pricingPlans = [
  {
    name: "Free",
    price: "₹0",
    period: "/month",
    tag: "Get Started",
    popular: false,
    buttonClass: "border-2 border-[#1B5E38] text-[#1B5E38] hover:bg-emerald-50",
    features: ["3 Crop Recommendations/month", "7-Day Weather Forecast", "Basic Market Prices", "2 Disease Scans/month", "10 AI Queries/day", "1 Farm Profile"],
    missing: ["Smart Irrigation", "30-Day Price Predictions", "Priority Support", "Advanced Analytics"],
  },
  {
    name: "Professional",
    price: "₹499",
    period: "/month",
    tag: "Most Popular",
    popular: true,
    buttonClass: "bg-[#1B5E38] text-white hover:bg-[#155030]",
    features: ["Everything in Free", "Unlimited Recommendations", "Smart Irrigation Schedules", "Unlimited Disease Scans", "Unlimited AI Queries", "10 Farm Profiles", "Weekly Market Reports", "SMS & App Alerts"],
    missing: ["Advanced Analytics", "API Access", "Dedicated Support"],
  },
  {
    name: "Enterprise",
    price: "₹1,299",
    period: "/month",
    tag: "Best Value",
    popular: false,
    buttonClass: "bg-gradient-to-r from-[#1B5E38] to-[#059669] text-white hover:opacity-90",
    features: ["Everything in Professional", "30-Day Price Predictions", "Advanced Farm Analytics", "Unlimited Farm Profiles", "Government Scheme Advisor", "Export Reports (PDF/CSV)", "API Access for IoT", "Dedicated 24/7 Support"],
    missing: [],
  },
];
